import type { Company,EmailDraft } from "@/lib/types";
export const dashboardMetrics=[{label:"Companies",value:"248",detail:"this month",trend:"+24",tone:"blue"},{label:"Emails queued",value:"42",detail:"awaiting approval",trend:"12",tone:"violet"},{label:"Reply rate",value:"9.2%",detail:"vs last month",trend:"+1.4%",tone:"green"},{label:"Interested",value:"17",detail:"need follow-up",trend:"+5",tone:"amber"}];
export const companies:Company[]=[
{id:"proto-labs",name:"Proto Labs Europe",initials:"PL",domain:"protolabs.eu",country:"Germany",segment:"Service bureau",fitScore:9,stage:"Interested",nextAction:"Reply today",tags:["PETG","ABS","Industrial"],contact:"Marie Vogel",email:"marie@protolabs.example",summary:"Rapid manufacturing partner serving industrial engineering teams across Europe. Likely demand for reliable PETG and ABS supply."},
{id:"nordic-print",name:"Nordic Print Works",initials:"NP",domain:"nordicprint.example",country:"Sweden",segment:"Print farm",fitScore:9,stage:"Replied",nextAction:"Review question",tags:["PLA","PETG","Bulk"],contact:"Erik Lund",email:"erik@nordicprint.example",summary:"Medium-size print farm producing functional parts and short production runs. Strong fit for bulk PLA and PETG."},
{id:"makerlab",name:"MakerLab Studio",initials:"MS",domain:"makerlab.example",country:"Netherlands",segment:"Makerspace",fitScore:8,stage:"Contacted",nextAction:"Follow up tomorrow",tags:["PLA","Education"],contact:"Sophie de Vries",email:"sophie@makerlab.example",summary:"Community makerspace with training programs and shared FDM printers. Likely preference for accessible PLA color ranges."},
{id:"fabriq",name:"Fabriq Industries",initials:"FI",domain:"fabriq.example",country:"France",segment:"Manufacturer",fitScore:8,stage:"Big order",nextAction:"Call at 15:00",tags:["ABS","Engineering","Bulk"],contact:"Lucas Martin",email:"lucas@fabriq.example",summary:"Industrial manufacturer evaluating additive manufacturing for jigs and fixtures. Potential high-volume engineering material order."},
{id:"form3d",name:"Form3D Solutions",initials:"F3",domain:"form3d.example",country:"United Kingdom",segment:"Service bureau",fitScore:7,stage:"New",nextAction:"Generate profile",tags:["TPU","PETG"],contact:"Alex Taylor",email:"alex@form3d.example",summary:"Design and prototyping bureau focused on product-development clients."},
{id:"techuni",name:"Central Tech University",initials:"CT",domain:"ctu.example",country:"Poland",segment:"University",fitScore:7,stage:"Contacted",nextAction:"Follow up in 2 days",tags:["PLA","Education"],contact:"Dr. Anna Kowalska",email:"anna@ctu.example",summary:"Engineering faculty operating several teaching labs with desktop FDM printers."}];
export const recentActivity=[{title:"Big-order signal detected",detail:"Fabriq Industries asked about 500 kg pricing",time:"12 minutes ago",tone:"green"},{title:"Reply received",detail:"Nordic Print Works asked about lead times",time:"48 minutes ago",tone:"blue"},{title:"Catalog generated",detail:"12 PETG products for Proto Labs Europe",time:"2 hours ago",tone:"violet"},{title:"Product sync complete",detail:"84 products checked, 3 updated",time:"Today, 08:02",tone:"amber"}];
export const emailDrafts:EmailDraft[]=[{id:"e1",company:"Proto Labs Europe",contact:"Marie Vogel",subject:"Reliable PETG supply for your production runs",preview:"I noticed your team supports fast-turnaround manufacturing across Europe…",step:1,scheduledFor:"Today, 14:20",status:"Needs approval"},{id:"e2",company:"MakerLab Studio",contact:"Sophie de Vries",subject:"Filament options for MakerLab workshops",preview:"Your hands-on training program looks like a great fit for our easy-print PLA range…",step:1,scheduledFor:"Tomorrow, 09:40",status:"Needs approval"},{id:"e3",company:"Central Tech University",contact:"Dr. Anna Kowalska",subject:"Materials for CTU engineering labs",preview:"I saw the additive manufacturing work in your engineering faculty…",step:2,scheduledFor:"Friday, 10:15",status:"Scheduled"}];
